services:
  evaluation-dev:
    network_mode: host
    build:
      context: image
      dockerfile: Dockerfile
    image: evaluation-instruments:local
    container_name: eval-dev
    hostname: eval
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/home/seismo/workspace

      # [From Extension] Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
